# frozen_string_literal: true

##
# rubocop:disable  Metrics/BlockLength
namespace :book_export do
  desc 'Updates book export template field mapping display names.'

  task set_field_mapping_names: :environment do
    field_names = {
      'isbn': 'ISBN',
      'ean': 'EAN',

      'binding': 'Binding',
      'author': 'Author',
      'title': 'Title',
      'edition': 'Edition',
      'publisher': 'Publisher',
      'publication_date': 'Pub Date',
      'grade': 'Grade',

      'copyright': 'Copyright',
      'copyright_year': 'Year',

      'edition_status_code': 'Status',
      'edition_status_date': 'Stat Date',

      'sales_rank': 'Sales Rank',
      'sales_rank_aug_average': 'Aug Rank',

      'total_offers': 'Total Offers',
      'comments': 'Comments',
      'edition_flag': 'Edition Flag',
      'new_edition_date': 'NEP Date',
      'out_of_print_date': 'OP Date',
      'trade_flag': 'Trade Flag',

      'list_price': 'List',
      'used_wholesale_price': 'MBS WH',
      'follet_wh': 'FHE WH',
      'nebraska_wh': 'NBC WH',
      'texas_wh': 'TBC WH',
      'new_wholesale_price': 'New WH',

      # custom fields
      'max_wh': 'Max WH',
      'company': 'Company',
      'oe_qa_jan_rank': 'OEJanRank',
      'oe_aug_rank': 'OE Aug Rank',
      'oe_list_price': 'OEList',
      'oe_two_years_wh_max': 'OE2YRWH',
      'oe_one_year_highest_wholesale_price': 'OE1YRWH',
      'oe_yearly_fbaz_rented_quantity': 'OE365RQF',
      'oe_yearly_fbaz_sold_quantity': 'OE365SQF',
      'oe_yearly_main_sold_quantity': 'OEPYSM',
      'amazon_orders_7ds': '7DS',
      'amazon_orders_30ds': '30DS',
      'amazon_orders_90ds': '90DS',
      'amazon_orders_180ds_sale': '180SP',
      'amazon_orders_180ds_rental': '180RP',

      'trade_in': 'Trade',
      'weekly_tradein': 'Weekly Trade',
      'weight': 'Weight',
      'amazon_price': 'AZ New',

      'fcb_price': 'FCB',
      'sales_rank_jan_average': 'Jan Rank',
      'fbaq': 'FBAQ',
      'inbq': 'INBQ',
      'orq': 'ORQC',
      'orq_ninety': 'ORQF',
      'orq_total': 'ORQT',

      'bz_j_sku_quantity': 'BZ&J Q',
      'total_quantity_supplier': 'TQS',
      'pnep': 'PNEP',
      'max_wholesale_comments': 'WH Comments',
      'fba_sku_quantity': 'FBAWQ',
      'oe_isbn': 'OE ISBN',
      'ne_isbn': 'NE ISBN',

      'total_quantity': 'TQ',
      'average_turns': 'AVG Turns',

      'weekly_sqm': '7SQM',
      'weekly_spm': '7SPM',
      'monthly_sqm': '30SQM',
      'monthly_spm': '30SPM',

      'weekly_sqf': '7SQF',
      'weekly_spf': '7SPF',
      'weekly_rqf': '7RQF',
      'weekly_rpf': '7RPF',

      'monthly_sqf': '30SQF',
      'monthly_spf': '30SPF',
      'monthly_rqf': '30RQF',
      'monthly_rpf': '30RPF',

      'main_price': 'MainP',

      'weekly_chegg_sale_quantity': 'CHQ',

      'monthly_nw': 'NW30',
      'monthly_w': 'W30',
      'subject': 'Subject',
      'oe_life': 'OE_Life',
      'c_life': 'C_Life',
      'r_life': 'R_Life',
      'life': 'Life',
      'max_all_wholesale_price': 'WH',

      'ninety_rpf': '90RPF',
      'ninety_spf': '90SPF',

      'one_eighty_w': '180W',
      'one_eighty_nw': '180NW',
      'one_eighty_rpf': '180RPF',
      'one_eighty_spf': '180SPF',

      'email_price': 'FBASP',
      'amazon_ca_listing': 'FBARP',
      'grid_lowest': 'BBAP',

      'amazon_rental': 'W',
      'amazon_rental_average': '7 days W',
      'ninety_w': '90W',

      'lowest_rental_august_average': 'NW3',
      'lowest_rental': 'NW',
      'lowest_rental_average': '7 days NW',
      'ninety_nw': '90NW',

      'lowest_price_aug_average': 'PC3',
      'lowest_price_jan_average': 'Jan PC3',
      'lowest_price': 'Low',
      'lowest_good_price': 'ALow',
      'amazon_ca_low': 'AmazonCA Low',
      'amazon_ca_new': 'AmazonCA New',
      'amazon_uk_low': 'AmazonUK Low',
      'amazon_uk_new': 'AmazonUK New',
      'weekly_low': 'Low7',
      'monthly_low': 'Low30',
      'ninety_low': 'Low90',
      'one_eighty_low': 'Low180',

      'fba_august_average': 'FB3',
      'fba_price': 'FBA Low',
      'weekly_fba': 'FBA7',
      'monthly_fba': 'FBA30',
      'ninety_fba': 'FBA90',
      'one_eighty_fba': 'FBA180',
      'not_in_guide': 'IN GUIDE',
      'valore_pending_order': 'PendQ',

      'low_jan_avg': 'JAN LOW AVG',
      'low_feb_avg': 'FEB LOW AVG',
      'low_mar_avg': 'MAR LOW AVG',
      'low_apr_avg': 'APR LOW AVG',
      'low_may_avg': 'MAY LOW AVG',
      'low_jun_avg': 'JUN LOW AVG',
      'low_jul_avg': 'JUL LOW AVG',
      'low_aug_avg': 'AUG LOW AVG',
      'low_sep_avg': 'SEP LOW AVG',
      'low_oct_avg': 'OCT LOW AVG',
      'low_nov_avg': 'NOV LOW AVG',
      'low_dec_avg': 'DEC LOW AVG',

      'fba_jan_avg': 'JAN FBA AVG',
      'fba_feb_avg': 'FEB FBA AVG',
      'fba_mar_avg': 'MAR FBA AVG',
      'fba_apr_avg': 'APR FBA AVG',
      'fba_may_avg': 'MAY FBA AVG',
      'fba_jun_avg': 'JUN FBA AVG',
      'fba_jul_avg': 'JUL FBA AVG',
      'fba_aug_avg': 'AUG FBA AVG',
      'fba_sep_avg': 'SEP FBA AVG',
      'fba_oct_avg': 'OCT FBA AVG',
      'fba_nov_avg': 'NOV FBA AVG',
      'fba_dec_avg': 'DEC FBA AVG',

      'sales_rank_jan_avg': 'JAN SALES RANK AVG',
      'sales_rank_feb_avg': 'FEB SALES RANK AVG',
      'sales_rank_mar_avg': 'MAR SALES RANK AVG',
      'sales_rank_apr_avg': 'APR SALES RANK AVG',
      'sales_rank_may_avg': 'MAY SALES RANK AVG',
      'sales_rank_jun_avg': 'JUN SALES RANK AVG',
      'sales_rank_jul_avg': 'JUL SALES RANK AVG',
      'sales_rank_aug_avg': 'AUG SALES RANK AVG',
      'sales_rank_sep_avg': 'SEP SALES RANK AVG',
      'sales_rank_oct_avg': 'OCT SALES RANK AVG',
      'sales_rank_nov_avg': 'NOV SALES RANK AVG',
      'sales_rank_dec_avg': 'DEC SALES RANK AVG',

      'ninety_accepted': '90Acc',

      'highest_weekly_low': 'PC365',

      'ninety_rqf': '90RQF',
      'one_eighty_rqf': '180RQF',
      'pricing_custom_14': 'FBA 2nd',

      'yearly_sold_quantity_all': 'PYSA',
      'yearly_main_sold_quantity': 'PYSM',
      'yearly_fbaz_sold_quantity': '365SQF',
      'yearly_fbaz_rented_quantity': '365RQF',
      'highest_weekly_low_average_last_seven_thirty': 'PC730',
      'competitive_sellers': 'Competitive Sellers',
      'yearly_main_sold_price': '365SPM',
      'yearly_fbaz_sold_price': '365SPF',
      'yearly_fbaz_rented_price': '365RPF',

      'buyouts': 'BOQ',
      'buyouts_percentage': 'BO%',

      'returns': 'RQ',
      'returns_percentage': 'R%',

      'third_fba': 'FBA 3rd',
      'supplier_price': 'Supplier Price',
      'fbaz_flag': 'FBAZ Flag',
      'main_flag': 'Main Flag',
      'fbaz_low': 'PC7',
      'fba_seventh': 'PC25',
      'peak_price': 'Peak Price',
      'roi': 'ROI',
      'monthly_amazon_trade_in': '30ATI',

      'yearly_low': 'YLow',
      'yearly_fba_low': 'YFBALow',

      'nw_jan_avg': 'JAN NW',
      'nw_feb_avg': 'FEB NW',
      'nw_mar_avg': 'MAR NW',
      'nw_apr_avg': 'APR NW',
      'nw_may_avg': 'MAY NW',
      'nw_jun_avg': 'JUNE NW',
      'nw_jul_avg': 'JULY NW',
      'nw_aug_avg': 'AUG NW',
      'nw_sep_avg': 'SEPT NW',
      'nw_oct_avg': 'OCT NW',
      'nw_nov_avg': 'NOV NW',
      'nw_dec_avg': 'DEC NW',

      'weekly_direct_qty_all': '7SQAD',
      'weekly_direct_price_all': '7SPAD',

      'weekly_direct_qty_main': '7SQMD',
      'pricing_custom_2': '7SPMD',

      'monthly_direct_qty_all': '30SQAD',
      'monthly_direct_price_all': '30SPAD',

      'monthly_sold_quantity_direct': '30SQMD',
      'monthly_direct_price_main': '30SPMD',

      'monthly_sold_quantity_all': '30SQA',
      'monthly_sold_price_all': '30SPA',

      'two_years_main_sold_quantity': 'P2YSM',
      'two_years_fbaz_sold_quantity': 'P2YSFS',
      'two_years_fbaz_rented_quantity': 'P2YSFR',
      'two_years_sold_quantity_all': 'P2YSA',

      'three_years_main_sold_quantity': 'P3YSM',
      'three_years_fbaz_sold_quantity': 'P3YSFS',
      'three_years_fbaz_rented_quantity': 'P3YSFR',
      'three_years_sold_quantity_all': 'P3YSA',

      'ninety_sold_quantity_all': '90SQA',
      'ninety_sold_price_all': '90SPA',

      'ninety_sold_quantity_main': '90SQM',
      'ninety_sold_price_main': '90SPM',

      'one_eighty_sale_quantity_all': '180SQA',
      'one_eighty_sale_price_all': '180SPA',

      'one_eighty_sale_quantity_main': '180SQM',
      'one_eighty_sale_price_main': '180SPM',

      'one_eighty_sale_quantity_fbaz': '180SQF',

      'weekly_sale_quantity_all': '7SQA',
      'weekly_sale_price_all': '7SPA',

      'book_scouter_1': 'BS1',
      'book_scouter_2': 'BS2',
      'book_scouter_3': 'BS3',
      'book_scouter_4': 'BS4',
      'book_scouter_5': 'BS5',
      'book_scouter_6': 'BS6',
      'book_scouter_7': 'BS7',

      'book_scouter_vendor_1': 'BSN1',
      'book_scouter_vendor_2': 'BSN2',
      'book_scouter_vendor_3': 'BSN3',
      'book_scouter_vendor_4': 'BSN4',
      'book_scouter_vendor_5': 'BSN5',
      'book_scouter_vendor_6': 'BSN6',
      'book_scouter_vendor_7': 'BSN7',
      'scraped_date': 'BSDate',

      'jan_rush_in_stock': 'InStockJan',
      'august_rush_in_stock': 'InStockAug',

      'new_box': 'NewBox',

      'main_quantity_in_inventory': 'MainQ',

      'forty_percent_rental': 'TR3',

      'qa_sales_rank': 'QaSalesRank',
      'qa_aug_rank': 'QaAugRank',
      'qa_jan_rank': 'QaJanRank',
      'qa_low': 'QaLow',
      'qa_aug_low': 'QaPC3',
      'qa_fba_low': 'QaFBALow',
      'qa_rent': 'QaRent',
      'rent_avg': 'RentAvg',
      'pricing_custom_12': 'SFBALow',
      'pricing_custom_15': 'SRental',

      'one_year_highest_wholesale_price': '1YRWH',
      'two_years_wh_max': '2YRWH',

      'valore_low': 'VLow',
      'valore_rent': 'VRent'
    }

    book_field_mappings = BookFieldMapping.all
    book_field_mappings.each do |field|
      name = field_names[field.lookup_field.to_sym]
      unless name.nil?
        field.update!(display_name: name)
        puts "Updated display name #{field.lookup_field}: #{name}"
      end
    end
  end

  task import_templates_from_outdaba: :environment do
    templates = [
      { "name": 'EAN', "fields": [
        { "position": 0, "name": 'ean' },
        { "position": 1, "name": 'isbn' },
        { "position": 2, "name": 'author' },
        { "position": 3, "name": 'title' },
        { "position": 4, "name": 'edition' },
        { "position": 5, "name": 'copyright' },
        { "position": 6, "name": 'oe_isbn' },
        { "position": 7, "name": 'max_wholesale_comments' },
        { "position": 8, "name": 'copyright_year' },
        { "position": 9, "name": 'comments' },
        { "position": 10, "name": 'binding' },
        { "position": 11, "name": 'edition_flag' },
        { "position": 12, "name": 'grade' },
        { "position": 13, "name": 'pnep' },
        { "position": 14, "name": 'publisher' },
        { "position": 15, "name": 'list_price' },
        { "position": 16, "name": 'trade_in' },
        { "position": 17, "name": 'lowest_price' },
        { "position": 18, "name": 'max_all_wholesale_price' }
      ] },
      { "name": 'Wholesale', "fields": [
        { "position": 0, "name": 'copyright' },
        { "position": 1, "name": 'copyright_year' },
        { "position": 2, "name": 'total_offers' },
        { "position": 3, "name": 'comments' },
        { "position": 4, "name": 'binding' },
        { "position": 5, "name": 'edition_flag' },
        { "position": 6, "name": 'new_edition_date' },
        { "position": 7, "name": 'out_of_print_date' },
        { "position": 8, "name": 'trade_flag' },
        { "position": 9, "name": 'new_wholesale_price' },
        { "position": 10, "name": 'amazon_price' },
        { "position": 11, "name": 'isbn' }
      ] },
      { "name": 'Brett', "fields": [
        { "position": 0, "name": 'isbn' },
        { "position": 1, "name": 'author' },
        { "position": 2, "name": 'title' },
        { "position": 3, "name": 'edition' },
        { "position": 4, "name": 'edition_status_code' },
        { "position": 5, "name": 'grade' },
        { "position": 6, "name": 'list_price' },
        { "position": 7, "name": 'max_all_wholesale_price' },
        { "position": 8, "name": 'lowest_price' },
        { "position": 9, "name": 'fcb_price' },
        { "position": 10, "name": 'trade_in' },
        { "position": 11, "name": 'lowest_price_aug_average' },
        { "position": 12, "name": 'main_price' },
        { "position": 13, "name": 'weight' }
      ] },
      { "name": 'Emily Wholesale', "fields": [
        { "position": 0, "name": 'comments' },
        { "position": 1, "name": 'list_price' },
        { "position": 2, "name": 'lowest_price' },
        { "position": 3, "name": 'sales_rank' },
        { "position": 4, "name": 'lowest_price_aug_average' }
      ] },
      { "name": 'temp', "fields": [
        { "position": 0, "name": 'author' },
        { "position": 1, "name": 'title' },
        { "position": 2, "name": 'edition' },
        { "position": 3, "name": 'copyright' },
        { "position": 4, "name": 'isbn' }
      ] },
      { "name": 'Stephanie', "fields": [
        { "position": 0, "name": 'isbn' },
        { "position": 1, "name": 'ean' },
        { "position": 2, "name": 'author' },
        { "position": 3, "name": 'title' },
        { "position": 4, "name": 'edition' },
        { "position": 5, "name": 'publisher' },
        { "position": 6, "name": 'publication_date' },
        { "position": 7, "name": 'grade' },
        { "position": 8, "name": 'list_price' },
        { "position": 9, "name": 'max_all_wholesale_price' },
        { "position": 10, "name": 'lowest_price' },
        { "position": 11, "name": 'lowest_price_aug_average' },
        { "position": 12, "name": 'sales_rank' },
        { "position": 13, "name": 'trade_in' },
        { "position": 14, "name": 'fbaq' },
        { "position": 15, "name": 'total_quantity' },
        { "position": 16, "name": 'total_quantity_supplier' },
        { "position": 17, "name": 'fba_price' },
        { "position": 18, "name": 'pricing_custom_2' },
        { "position": 19, "name": 'main_price' },
        { "position": 20, "name": 'bz_j_sku_quantity' },
        { "position": 21, "name": 'sales_rank_aug_average' },
        { "position": 22, "name": 'orq_total' },
        { "position": 23, "name": 'fba_sku_quantity' },
        { "position": 24, "name": 'inbq' },
        { "position": 25, "name": 'max_wholesale_comments' },
        { "position": 26, "name": 'weekly_direct_price_all' },
        { "position": 27, "name": 'monthly_direct_price_all' },
        { "position": 28, "name": 'ne_isbn' },
        { "position": 29, "name": 'one_eighty_sale_quantity_fbaz' },
        { "position": 30, "name": 'one_eighty_rqf' },
        { "position": 31, "name": 'monthly_direct_qty_all' },
        { "position": 32, "name": 'one_eighty_sale_quantity_all' },
        { "position": 33, "name": 'amazon_uk_new' },
        { "position": 34, "name": 'oe_isbn' },
        { "position": 35, "name": 'oe_aug_rank' },
        { "position": 36, "name": 'amazon_ca_new' },
        { "position": 37, "name": 'amazon_rental' },
        { "position": 38, "name": 'lowest_rental' },
        { "position": 39, "name": 'comments' },
        { "position": 40, "name": 'main_flag' },
        { "position": 41, "name": 'amazon_orders_180ds_sale' },
        { "position": 42, "name": 'one_eighty_low' },
        { "position": 43, "name": 'one_eighty_sale_quantity_main' },
        { "position": 46, "name": 'book_scouter_1' },
        { "position": 48, "name": 'lowest_good_price' },
        { "position": 49, "name": 'used_wholesale_price' },
        { "position": 50, "name": 'nebraska_wh' },
        { "position": 51, "name": 'texas_wh' },
        { "position": 52, "name": 'edition_status_date' },
        { "position": 53, "name": 'out_of_print_date' }
      ] },
      { "name": 'Slam Dunk', "fields": [
        { "position": 0, "name": 'ean' },
        { "position": 1, "name": 'isbn' },
        { "position": 2, "name": 'author' },
        { "position": 3, "name": 'title' },
        { "position": 4, "name": 'edition' },
        { "position": 5, "name": 'publication_date' },
        { "position": 6, "name": 'publisher' },
        { "position": 7, "name": 'total_quantity' },
        { "position": 8, "name": 'fbaq' },
        { "position": 9, "name": 'inbq' },
        { "position": 10, "name": 'orq_total' },
        { "position": 11, "name": 'total_quantity_supplier' },
        { "position": 12, "name": 'grade' },
        { "position": 13, "name": 'edition_status_code' },
        { "position": 14, "name": 'edition_status_date' },
        { "position": 15, "name": 'list_price' },
        { "position": 16, "name": 'qa_aug_low' },
        { "position": 17, "name": 'used_wholesale_price' },
        { "position": 18, "name": 'nebraska_wh' },
        { "position": 19, "name": 'texas_wh' },
        { "position": 20, "name": 'qa_low' },
        { "position": 21, "name": 'fba_price' },
        { "position": 22, "name": 'yearly_low' },
        { "position": 23, "name": 'yearly_fba_low' },
        { "position": 24, "name": 'qa_rent' },
        { "position": 25, "name": 'qa_sales_rank' },
        { "position": 26, "name": 'qa_aug_rank' },
        { "position": 27, "name": 'qa_jan_rank' },
        { "position": 28, "name": 'yearly_fbaz_rented_quantity' },
        { "position": 29, "name": 'yearly_fbaz_rented_price' },
        { "position": 30, "name": 'yearly_fbaz_sold_quantity' },
        { "position": 31, "name": 'yearly_fbaz_sold_price' },
        { "position": 32, "name": 'monthly_rqf' },
        { "position": 33, "name": 'monthly_rpf' },
        { "position": 34, "name": 'monthly_sqf' },
        { "position": 35, "name": 'monthly_spf' },
        { "position": 36, "name": 'one_eighty_rqf' },
        { "position": 37, "name": 'one_eighty_rpf' },
        { "position": 38, "name": 'monthly_sqm' },
        { "position": 39, "name": 'monthly_spm' },
        { "position": 40, "name": 'one_eighty_sale_quantity_main' },
        { "position": 41, "name": 'one_eighty_sale_price_main' },
        { "position": 42, "name": 'yearly_sold_quantity_all' },
        { "position": 43, "name": 'two_years_sold_quantity_all' },
        { "position": 44, "name": 'three_years_sold_quantity_all' },
        { "position": 45, "name": 'monthly_direct_qty_all' },
        { "position": 46, "name": 'monthly_direct_price_all' },
        { "position": 47, "name": 'one_eighty_sale_quantity_all' },
        { "position": 48, "name": 'one_eighty_sale_price_all' },
        { "position": 49, "name": 'book_scouter_1' },
        { "position": 50, "name": 'book_scouter_2' },
        { "position": 51, "name": 'book_scouter_3' },
        { "position": 52, "name": 'subject' },
        { "position": 53, "name": 'r_life' },
        { "position": 54, "name": 'oe_isbn' },
        { "position": 55, "name": 'oe_aug_rank' },
        { "position": 56, "name": 'oe_life' },
        { "position": 57, "name": 'oe_yearly_fbaz_rented_quantity' },
        { "position": 58, "name": 'oe_yearly_fbaz_sold_quantity' },
        { "position": 59, "name": 'oe_yearly_main_sold_quantity' },
        { "position": 60, "name": 'copyright' },
        { "position": 61, "name": 'ninety_low' },
        { "position": 62, "name": 'one_eighty_low' },
        { "position": 63, "name": 'one_year_highest_wholesale_price' },
        { "position": 64, "name": 'valore_pending_order' },
        { "position": 65, "name": 'lowest_good_price' },
        { "position": 66, "name": 'valore_low' },
        { "position": 67, "name": 'main_price' },
        { "position": 68, "name": 'email_price' },
        { "position": 69, "name": 'main_flag' },
        { "position": 70, "name": 'amazon_ca_new' },
        { "position": 71, "name": 'yearly_main_sold_quantity' },
        { "position": 72, "name": 'weekly_rqf' },
        { "position": 73, "name": 'weekly_rpf' },
        { "position": 74, "name": 'weekly_sqm' },
        { "position": 75, "name": 'weekly_spm' }
      ] },
      { "name": '180RP', "fields": [
        { "position": 0, "name": 'ean' },
        { "position": 1, "name": 'isbn' },
        { "position": 2, "name": 'amazon_orders_180ds_rental' },
        # TODO: {"position": 3, "name": "(SELECT amazon_trade.last_submitted_price FROM amazon_trade WHERE amazon_trade.product_id = product_id)"}.
        { "position": 4, "name": 'binding' }
      ] },
      { "name": 'kyle', "fields": [
        { "position": 0, "name": 'isbn' },
        { "position": 1, "name": 'ean' },
        { "position": 2, "name": 'yearly_fbaz_sold_quantity' },
        { "position": 3, "name": 'yearly_fbaz_rented_quantity' },
        { "position": 4, "name": 'fbaq' },
        { "position": 5, "name": 'orq_total' },
        { "position": 6, "name": 'bz_j_sku_quantity' },
        { "position": 7, "name": 'author' },
        { "position": 8, "name": 'title' },
        { "position": 9, "name": 'edition' },
        { "position": 10, "name": 'grade' },
        { "position": 11, "name": 'edition_status_code' },
        { "position": 12, "name": 'edition_status_date' },
        { "position": 13, "name": 'list_price' },
        { "position": 14, "name": 'max_all_wholesale_price' },
        { "position": 15, "name": 'lowest_price_aug_average' },
        { "position": 16, "name": 'lowest_price' },
        { "position": 17, "name": 'fba_price' },
        { "position": 18, "name": 'sales_rank_jan_average' },
        { "position": 19, "name": 'sales_rank_aug_average' },
        { "position": 20, "name": 'sales_rank' },
        { "position": 21, "name": 'publisher' },
        { "position": 22, "name": 'publication_date' },
        { "position": 23, "name": 'lowest_rental' },
        { "position": 24, "name": 'fcb_price' },
        { "position": 25, "name": 'trade_in' },
        { "position": 26, "name": 'r_life' },
        { "position": 27, "name": 'monthly_sqf' },
        { "position": 28, "name": 'monthly_rqf' },
        { "position": 29, "name": 'monthly_sqm' }
      ] },
      { "name": 'Kyle 2', "fields": [
        { "position": 0, "name": 'isbn' },
        { "position": 1, "name": 'fbaq' },
        { "position": 2, "name": 'inbq' },
        { "position": 3, "name": 'orq' },
        { "position": 4, "name": 'total_quantity' },
        { "position": 5, "name": 'author' },
        { "position": 6, "name": 'title' },
        { "position": 7, "name": 'edition' },
        { "position": 8, "name": 'grade' },
        { "position": 9, "name": 'edition_status_code' },
        { "position": 1, "name": 'list_price' },
        { "position": 11, "name": 'max_all_wholesale_price' },
        { "position": 12, "name": 'lowest_price' },
        { "position": 13, "name": 'lowest_price_aug_average' },
        { "position": 14, "name": 'fba_price' },
        { "position": 15, "name": 'lowest_rental' },
        { "position": 16, "name": 'sales_rank_jan_average' },
        { "position": 17, "name": 'sales_rank_aug_average' },
        { "position": 18, "name": 'sales_rank' },
        { "position": 19, "name": 'publisher' },
        { "position": 20, "name": 'publication_date' },
        { "position": 21, "name": 'fcb_price' },
        { "position": 22, "name": 'trade_in' },
        { "position": 23, "name": 'subject' },
        { "position": 24, "name": 'amazon_price' },
        { "position": 25, "name": 'main_price' },
        { "position": 26, "name": 'ean' },
        { "position": 27, "name": 'binding' },
        { "position": 28, "name": 'oe_isbn' },
        { "position": 29, "name": 'email_price' },
        { "position": 30, "name": 'used_wholesale_price' },
        { "position": 31, "name": 'follet_wh' },
        { "position": 32, "name": 'nebraska_wh' },
        { "position": 33, "name": 'company' },
        { "position": 34, "name": 'pricing_custom_14' },
        { "position": 35, "name": 'bz_j_sku_quantity' },
        { "position": 36, "name": 'low_jan_avg' },
        { "position": 37, "name": 'low_aug_avg' },
        { "position": 38, "name": 'yearly_low' },
        { "position": 39, "name": 'fba_sku_quantity' },
        { "position": 40, "name": 'book_scouter_1' },
        { "position": 41, "name": 'weekly_direct_qty_all' },
        { "position": 42, "name": 'total_quantity_supplier' },
        { "position": 43, "name": 'weekly_direct_qty_main' },
        { "position": 44, "name": 'orq_total' },
        { "position": 45, "name": 'ne_isbn' },
        { "position": 46, "name": 'yearly_fbaz_sold_quantity' },
        { "position": 47, "name": 'yearly_main_sold_quantity' },
        { "position": 48, "name": 'yearly_fbaz_rented_quantity' },
        { "position": 49, "name": 'weekly_sqf' },
        { "position": 50, "name": 'weekly_rqf' },
        { "position": 51, "name": 'weekly_direct_price_all' },
        { "position": 52, "name": 'monthly_direct_qty_all' },
        { "position": 53, "name": 'monthly_direct_price_all' },
        { "position": 54, "name": 'monthly_sold_quantity_direct' },
        { "position": 55, "name": 'monthly_direct_price_main' },
        { "position": 56, "name": 'monthly_spf' },
        { "position": 57, "name": 'monthly_sqf' },
        { "position": 58, "name": 'monthly_rqf' },
        { "position": 59, "name": 'monthly_rpf' },
        { "position": 60, "name": 'monthly_sqm' },
        { "position": 61, "name": 'main_quantity_in_inventory' },
        { "position": 62, "name": 'amazon_ca_new' },
        { "position": 63, "name": 'edition_status_date' },
        { "position": 64, "name": 'pricing_custom_2' },
        { "position": 65, "name": 'valore_low' },
        { "position": 66, "name": 'weight' }
      ] },
      { "name": 'FBA Low', "fields": [
        { "position": 0, "name": 'isbn' },
        { "position": 1, "name": 'title' },
        { "position": 2, "name": 'author' },
        { "position": 3, "name": 'fba_price' }
      ] },
      { "name": 'Houston Hunter', "fields": [
        { "position": 0, "name": 'fba_jun_avg' },
        { "position": 1, "name": 'fba_jul_avg' },
        { "position": 2, "name": 'fba_aug_avg' },
        { "position": 3, "name": 'fba_sep_avg' },
        { "position": 4, "name": 'fba_oct_avg' },
        { "position": 5, "name": 'fba_nov_avg' },
        { "position": 6, "name": 'fba_dec_avg' },
        { "position": 7, "name": 'fba_jan_avg' },
        { "position": 8, "name": 'fba_feb_avg' },
        { "position": 9, "name": 'fba_mar_avg' },
        { "position": 10, "name": 'fba_apr_avg' },
        { "position": 11, "name": 'sales_rank_jun_avg' },
        { "position": 12, "name": 'sales_rank_jul_avg' },
        { "position": 13, "name": 'sales_rank_aug_avg' },
        { "position": 14, "name": 'sales_rank_sep_avg' },
        { "position": 15, "name": 'sales_rank_oct_avg' },
        { "position": 16, "name": 'sales_rank_nov_avg' },
        { "position": 17, "name": 'sales_rank_dec_avg' },
        { "position": 18, "name": 'sales_rank_jan_avg' },
        { "position": 19, "name": 'sales_rank_feb_avg' },
        { "position": 20, "name": 'sales_rank_mar_avg' },
        { "position": 21, "name": 'sales_rank_apr_avg' },
        { "position": 22, "name": 'sales_rank_may_avg' },
        { "position": 23, "name": 'fba_may_avg' },
        { "position": 24, "name": 'isbn' }
      ] },
      { "name": 'rental v sell', "fields": [
        { "position": 0, "name": 'isbn' },
        { "position": 1, "name": 'subject' },
        { "position": 2, "name": 'amazon_ca_listing' },
        { "position": 3, "name": 'email_price' },
        { "position": 4, "name": 'list_price' }
      ] },
      { "name": 'Direct Auto-Buy', "fields": [
        { "position": 0, "name": 'fbaq' },
        { "position": 1, "name": 'inbq' },
        { "position": 2, "name": 'orq_total' },
        { "position": 3, "name": 'fba_sku_quantity' },
        { "position": 4, "name": 'bz_j_sku_quantity' },
        { "position": 5, "name": 'isbn' },
        { "position": 6, "name": 'author' },
        { "position": 7, "name": 'title' },
        { "position": 8, "name": 'edition' },
        { "position": 9, "name": 'grade' },
        { "position": 10, "name": 'edition_status_code' },
        { "position": 11, "name": 'edition_status_date' },
        { "position": 12, "name": 'list_price' },
        { "position": 13, "name": 'max_all_wholesale_price' },
        { "position": 14, "name": 'lowest_price_aug_average' },
        { "position": 15, "name": 'lowest_price' },
        { "position": 16, "name": 'fba_price' },
        { "position": 17, "name": 'sales_rank_jan_average' },
        { "position": 18, "name": 'sales_rank_aug_average' },
        { "position": 19, "name": 'sales_rank' },
        { "position": 20, "name": 'publisher' },
        { "position": 21, "name": 'publication_date' },
        { "position": 22, "name": 'weekly_sqf' },
        { "position": 23, "name": 'weekly_spf' },
        { "position": 24, "name": 'monthly_fba' }
      ] },
      { "name": 'test', "fields": [
        { "position": 0, "name": 'pricing_custom_14' }
      ] },
      { "name": 'Wholesale Drop', "fields": [
        { "position": 0, "name": 'isbn' },
        { "position": 1, "name": 'author' },
        { "position": 2, "name": 'title' },
        { "position": 3, "name": 'edition' },
        { "position": 4, "name": 'grade' },
        { "position": 5, "name": 'edition_status_code' },
        { "position": 6, "name": 'edition_status_date' },
        { "position": 7, "name": 'list_price' },
        { "position": 8, "name": 'lowest_price_aug_average' },
        { "position": 9, "name": 'lowest_price' },
        { "position": 10, "name": 'fba_august_average' },
        { "position": 11, "name": 'copyright_year' },
        { "position": 12, "name": 'publisher' },
        { "position": 13, "name": 'publication_date' },
        { "position": 14, "name": 'lowest_rental_august_average' },
        { "position": 15, "name": 'one_eighty_w' },
        { "position": 16, "name": 'binding' },
        { "position": 17, "name": 'used_wholesale_price' },
        { "position": 18, "name": 'follet_wh' },
        { "position": 19, "name": 'nebraska_wh' },
        { "position": 20, "name": 'third_fba' },
        { "position": 21, "name": 'ninety_low' },
        { "position": 22, "name": 'ninety_fba' },
        { "position": 23, "name": 'total_offers' },
        { "position": 24, "name": 'one_eighty_spf' },
        { "position": 25, "name": 'ninety_rpf' },
        { "position": 26, "name": 'ninety_rqf' },
        { "position": 27, "name": 'competitive_sellers' },
        { "position": 28, "name": 'fba_price' },
        { "position": 29, "name": 'monthly_fba' },
        { "position": 30, "name": 'amazon_price' },
        { "position": 31, "name": 'sales_rank' },
        { "position": 32, "name": 'sales_rank_aug_average' },
        { "position": 33, "name": 'sales_rank_jan_average' },
        { "position": 34, "name": 'lowest_rental' },
        { "position": 35, "name": 'amazon_rental' },
        { "position": 36, "name": 'monthly_nw' },
        { "position": 37, "name": 'monthly_w' },
        { "position": 38, "name": 'yearly_low' },
        { "position": 39, "name": 'yearly_fba_low' },
        { "position": 40, "name": 'bz_j_sku_quantity' },
        { "position": 41, "name": 'fba_sku_quantity' }
      ] },
      { "name": 'last year sales', "fields": [
        { "position": 0, "name": 'isbn' },
        { "position": 1, "name": 'one_eighty_low' },
        { "position": 2, "name": 'one_eighty_fba' },
        { "position": 3, "name": 'fbaq' }
      ] },
      { "name": 'wantlist check', "fields": [
        { "position": 0, "name": 'fbaq' },
        { "position": 1, "name": 'fba_sku_quantity' },
        { "position": 2, "name": 'inbq' },
        { "position": 3, "name": 'isbn' },
        { "position": 4, "name": 'author' },
        { "position": 5, "name": 'title' },
        { "position": 6, "name": 'edition' },
        { "position": 7, "name": 'publisher' },
        { "position": 8, "name": 'publication_date' },
        { "position": 9, "name": 'grade' },
        { "position": 10, "name": 'edition_status_code' },
        { "position": 11, "name": 'list_price' },
        { "position": 12, "name": 'max_all_wholesale_price' },
        { "position": 13, "name": 'lowest_price' },
        { "position": 14, "name": 'fba_price' },
        { "position": 15, "name": 'sales_rank' },
        { "position": 16, "name": 'weekly_sqf' },
        { "position": 17, "name": 'weekly_spf' },
        { "position": 18, "name": 'weekly_sqm' },
        { "position": 19, "name": 'weekly_spm' },
        { "position": 20, "name": 'weekly_rqf' },
        { "position": 21, "name": 'weekly_rpf' },
        { "position": 22, "name": 'monthly_sqf' },
        { "position": 23, "name": 'monthly_sqm' },
        { "position": 24, "name": 'monthly_rqf' },
        { "position": 25, "name": 'yearly_main_sold_quantity' },
        { "position": 26, "name": 'yearly_fbaz_sold_quantity' },
        { "position": 27, "name": 'yearly_fbaz_rented_quantity' },
        { "position": 28, "name": 'oe_isbn' },
        { "position": 29, "name": 'oe_aug_rank' },
        { "position": 30, "name": 'oe_life' },
        { "position": 31, "name": 'ean' },
        { "position": 32, "name": 'total_quantity' }
      ] },
      { "name": 'binding', "fields": [
        { "position": 0, "name": 'isbn' },
        { "position": 1, "name": 'binding' }
      ] },
      { "name": 'Price Check', "fields": [
        { "position": 0, "name": 'fbaq' },
        { "position": 1, "name": 'inbq' },
        { "position": 2, "name": 'orq' },
        { "position": 3, "name": 'fba_sku_quantity' },
        { "position": 4, "name": 'bz_j_sku_quantity' },
        { "position": 5, "name": 'author' },
        { "position": 6, "name": 'title' },
        { "position": 7, "name": 'edition' },
        { "position": 8, "name": 'grade' },
        { "position": 9, "name": 'edition_status_code' },
        { "position": 10, "name": 'edition_status_date' },
        { "position": 11, "name": 'list_price' },
        { "position": 12, "name": 'max_all_wholesale_price' },
        { "position": 13, "name": 'lowest_price_aug_average' },
        { "position": 14, "name": 'lowest_price' },
        { "position": 15, "name": 'fba_price' },
        { "position": 16, "name": 'sales_rank_jan_average' },
        { "position": 17, "name": 'sales_rank_aug_average' },
        { "position": 18, "name": 'sales_rank' },
        { "position": 19, "name": 'publisher' },
        { "position": 20, "name": 'publication_date' },
        { "position": 21, "name": 'lowest_rental' },
        { "position": 22, "name": 'amazon_rental' },
        { "position": 23, "name": 'monthly_nw' },
        { "position": 24, "name": 'monthly_w' },
        { "position": 25, "name": 'fcb_price' },
        { "position": 26, "name": 'trade_in' },
        { "position": 27, "name": 'isbn' },
        { "position": 28, "name": 'ean' },
        { "position": 29, "name": 'oe_aug_rank' },
        { "position": 30, "name": 'oe_isbn' },
        { "position": 31, "name": 'new_box' },
        { "position": 32, "name": 'yearly_main_sold_quantity' },
        { "position": 33, "name": 'yearly_fbaz_sold_quantity' },
        { "position": 34, "name": 'yearly_fbaz_rented_quantity' },
        { "position": 35, "name": 'monthly_fba' },
        { "position": 36, "name": 'orq_total' },
        { "position": 37, "name": 'lowest_price_jan_average' },
        { "position": 38, "name": 'binding' },
        { "position": 39, "name": 'used_wholesale_price' },
        { "position": 40, "name": 'follet_wh' },
        { "position": 41, "name": 'nebraska_wh' },
        { "position": 42, "name": 'yearly_low' },
        { "position": 43, "name": 'yearly_fba_low' },
        { "position": 44, "name": 'email_price' },
        { "position": 45, "name": 'amazon_ca_listing' },
        { "position": 46, "name": 'main_price' },
        { "position": 47, "name": 'total_quantity' },
        { "position": 48, "name": 'grid_lowest' },
        { "position": 49, "name": 'weekly_sqf' },
        { "position": 50, "name": 'weekly_spf' },
        { "position": 51, "name": 'weekly_rqf' },
        { "position": 52, "name": 'weekly_rpf' },
        { "position": 53, "name": 'pricing_custom_14' },
        { "position": 54, "name": 'book_scouter_1' },
        { "position": 55, "name": 'book_scouter_2' },
        { "position": 56, "name": 'book_scouter_3' },
        { "position": 57, "name": 'book_scouter_4' },
        { "position": 58, "name": 'book_scouter_5' },
        { "position": 59, "name": 'book_scouter_6' },
        { "position": 60, "name": 'book_scouter_7' },
        { "position": 61, "name": 'amazon_ca_low' },
        { "position": 62, "name": 'amazon_ca_new' },
        { "position": 63, "name": 'weekly_direct_qty_all' },
        { "position": 64, "name": 'weekly_direct_price_all' },
        { "position": 65, "name": 'weekly_direct_qty_main' },
        { "position": 66, "name": 'pricing_custom_2' },
        { "position": 67, "name": 'monthly_direct_qty_all' },
        { "position": 68, "name": 'monthly_direct_price_all' },
        { "position": 69, "name": 'monthly_sold_quantity_direct' },
        { "position": 70, "name": 'monthly_direct_price_main' },
        { "position": 71, "name": 'total_quantity_supplier' },
        { "position": 72, "name": 'subject' },
        { "position": 73, "name": 'one_eighty_sale_quantity_fbaz' },
        { "position": 74, "name": 'one_eighty_spf' },
        { "position": 75, "name": 'one_eighty_rqf' },
        { "position": 76, "name": 'one_eighty_rpf' },
        { "position": 77, "name": 'one_eighty_sale_quantity_main' },
        { "position": 78, "name": 'one_eighty_sale_price_main' },
        { "position": 79, "name": 'ne_isbn' },
        { "position": 80, "name": 'low_jan_avg' },
        { "position": 81, "name": 'low_feb_avg' },
        { "position": 82, "name": 'low_mar_avg' },
        { "position": 83, "name": 'low_apr_avg' },
        { "position": 84, "name": 'low_may_avg' },
        { "position": 85, "name": 'low_jun_avg' },
        { "position": 86, "name": 'low_jul_avg' },
        { "position": 87, "name": 'low_aug_avg' },
        { "position": 88, "name": 'low_sep_avg' },
        { "position": 89, "name": 'low_oct_avg' },
        { "position": 90, "name": 'low_nov_avg' },
        { "position": 91, "name": 'low_dec_avg' },
        { "position": 92, "name": 'main_flag' },
        { "position": 93, "name": 'jan_rush_in_stock' },
        { "position": 94, "name": 'august_rush_in_stock' },
        { "position": 95, "name": 'amazon_orders_90ds' },
        { "position": 96, "name": 'ninety_spf' },
        { "position": 97, "name": 'ninety_rqf' },
        { "position": 98, "name": 'ninety_rpf' },
        { "position": 99, "name": 'monthly_sqf' },
        { "position": 100, "name": 'monthly_spf' },
        { "position": 101, "name": 'monthly_rqf' },
        { "position": 102, "name": 'monthly_rpf' },
        { "position": 103, "name": 'ninety_nw' },
        { "position": 104, "name": 'ninety_w' },
        { "position": 105, "name": 'one_eighty_w' },
        { "position": 106, "name": 'one_eighty_nw' },
        { "position": 107, "name": 'sales_rank_jan_avg' },
        { "position": 108, "name": 'sales_rank_aug_avg' },
        { "position": 109, "name": 'weekly_sqm' },
        { "position": 110, "name": 'weekly_spm' },
        { "position": 111, "name": 'monthly_sqm' },
        { "position": 112, "name": 'monthly_spm' },
        { "position": 113, "name": 'r_life' },
        { "position": 114, "name": 'amazon_price' },
        { "position": 115, "name": 'fbaz_flag' },
        { "position": 116, "name": 'pricing_custom_12' },
        { "position": 117, "name": 'pricing_custom_15' },
        { "position": 118, "name": 'forty_percent_rental' },
        { "position": 119, "name": 'ninety_sold_quantity_all' },
        { "position": 120, "name": 'ninety_sold_price_all' },
        { "position": 121, "name": 'ninety_sold_quantity_main' },
        { "position": 122, "name": 'ninety_sold_price_main' },
        { "position": 123, "name": 'fba_jan_avg' },
        { "position": 124, "name": 'fba_feb_avg' },
        { "position": 125, "name": 'fba_mar_avg' },
        { "position": 126, "name": 'fba_apr_avg' },
        { "position": 127, "name": 'fba_may_avg' },
        { "position": 128, "name": 'fba_jun_avg' },
        { "position": 129, "name": 'fba_jul_avg' },
        { "position": 130, "name": 'fba_aug_avg' },
        { "position": 131, "name": 'fba_sep_avg' },
        { "position": 132, "name": 'fba_oct_avg' },
        { "position": 133, "name": 'fba_nov_avg' },
        { "position": 134, "name": 'fba_dec_avg' },
        { "position": 135, "name": 'lowest_good_price' },
        { "position": 136, "name": 'one_year_highest_wholesale_price' },
        { "position": 137, "name": 'two_years_wh_max' },
        { "position": 138, "name": 'weight' },
        { "position": 139, "name": 'one_eighty_sale_quantity_all' },
        { "position": 140, "name": 'one_eighty_sale_price_all' }
      ] },
      { "name": 'direct test', "fields": [
        { "position": 0, "name": 'isbn' },
        { "position": 1, "name": 'weekly_direct_qty_main' },
        { "position": 2, "name": 'weekly_direct_qty_all' }
      ] },
      { "name": 'Amz Low', "fields": [
        { "position": 0, "name": 'ean' },
        { "position": 1, "name": 'lowest_price' }
      ] },
      { "name": 'Restock', "fields": [
        { "position": 0, "name": 'isbn' },
        { "position": 1, "name": 'ean' },
        { "position": 2, "name": 'orq_total' },
        { "position": 3, "name": 'orq' },
        { "position": 4, "name": 'one_eighty_rqf' }
      ] },
      { "name": 'AutoBuy', "fields": [
        { "position": 0, "name": 'ean' },
        { "position": 1, "name": 'isbn' },
        { "position": 2, "name": 'total_quantity_supplier' },
        { "position": 3, "name": 'total_quantity' },
        { "position": 4, "name": 'fbaq' },
        { "position": 5, "name": 'inbq' },
        { "position": 6, "name": 'orq_total' },
        { "position": 7, "name": 'author' },
        { "position": 8, "name": 'title' },
        { "position": 9, "name": 'edition' },
        { "position": 10, "name": 'grade' },
        { "position": 11, "name": 'edition_status_code' },
        { "position": 12, "name": 'edition_status_date' },
        { "position": 13, "name": 'list_price' },
        { "position": 14, "name": 'used_wholesale_price' },
        { "position": 15, "name": 'follet_wh' },
        { "position": 16, "name": 'nebraska_wh' },
        { "position": 17, "name": 'qa_aug_low' },
        { "position": 18, "name": 'qa_low' },
        { "position": 19, "name": 'qa_fba_low' },
        { "position": 20, "name": 'pricing_custom_12' },
        { "position": 21, "name": 'qa_rent' },
        { "position": 22, "name": 'pricing_custom_15' },
        { "position": 23, "name": 'qa_jan_rank' },
        { "position": 24, "name": 'qa_aug_rank' },
        { "position": 25, "name": 'qa_sales_rank' },
        { "position": 26, "name": 'publisher' },
        { "position": 27, "name": 'publication_date' },
        { "position": 28, "name": 'trade_in' },
        { "position": 29, "name": 'book_scouter_1' },
        { "position": 30, "name": 'book_scouter_2' },
        { "position": 31, "name": 'book_scouter_3' },
        { "position": 32, "name": 'book_scouter_4' },
        { "position": 33, "name": 'monthly_sqf' },
        { "position": 34, "name": 'monthly_spf' },
        { "position": 35, "name": 'monthly_rqf' },
        { "position": 36, "name": 'monthly_rpf' },
        { "position": 37, "name": 'one_eighty_sale_quantity_fbaz' },
        { "position": 38, "name": 'one_eighty_spf' },
        { "position": 39, "name": 'one_eighty_rqf' },
        { "position": 40, "name": 'one_eighty_rpf' },
        { "position": 41, "name": 'yearly_low' },
        { "position": 42, "name": 'yearly_fba_low' },
        { "position": 43, "name": 'yearly_main_sold_quantity' },
        { "position": 44, "name": 'yearly_fbaz_sold_quantity' },
        { "position": 45, "name": 'yearly_fbaz_rented_quantity' },
        { "position": 46, "name": 'amazon_price' }
      ] },
      { "name": 'Wantlist', "fields": [
        { "position": 0, "name": 'isbn' },
        { "position": 1, "name": 'author' },
        { "position": 2, "name": 'title' },
        { "position": 3, "name": 'edition' },
        { "position": 4, "name": 'publisher' },
        { "position": 5, "name": 'publication_date' },
        { "position": 6, "name": 'grade' },
        { "position": 7, "name": 'list_price' },
        { "position": 8, "name": 'max_all_wholesale_price' },
        { "position": 9, "name": 'lowest_price' },
        { "position": 10, "name": 'fba_price' },
        { "position": 11, "name": 'lowest_price_aug_average' },
        { "position": 12, "name": 'lowest_rental' },
        { "position": 13, "name": 'amazon_rental' },
        { "position": 14, "name": 'fbaq' },
        { "position": 15, "name": 'inbq' },
        { "position": 16, "name": 'orq_total' },
        { "position": 17, "name": 'total_quantity_supplier' },
        { "position": 18, "name": 'total_quantity' },
        { "position": 19, "name": 'sales_rank' },
        { "position": 20, "name": 'sales_rank_aug_average' },
        { "position": 21, "name": 'oe_isbn' },
        { "position": 22, "name": 'oe_aug_rank' },
        { "position": 23, "name": 'oe_life' },
        { "position": 24, "name": 'qa_rent' }
      ] },
      { "name": 'MW Price Check', "fields": [
        { "position": 0, "name": 'isbn' },
        { "position": 1, "name": 'ean' },
        { "position": 2, "name": 'author' },
        { "position": 3, "name": 'title' },
        { "position": 4, "name": 'edition' },
        { "position": 5, "name": 'comments' },
        { "position": 6, "name": 'list_price' },
        { "position": 7, "name": 'max_wh' },
        { "position": 8, "name": 'lowest_price' },
        { "position": 9, "name": 'weekly_low' },
        { "position": 10, "name": 'lowest_price_aug_average' },
        { "position": 11, "name": 'sales_rank' },
        { "position": 12, "name": 'fba_price' },
        { "position": 13, "name": 'trade_in' },
        { "position": 14, "name": 'fbaq' },
        { "position": 15, "name": 'supplier_price' }
      ] },
      { "name": 'SalesRanks', "fields": [
        { "position": 0, "name": 'isbn' },
        { "position": 1, "name": 'sales_rank_jan_avg' },
        { "position": 2, "name": 'sales_rank_feb_avg' },
        { "position": 3, "name": 'sales_rank_mar_avg' },
        { "position": 4, "name": 'sales_rank_apr_avg' },
        { "position": 5, "name": 'sales_rank_may_avg' },
        { "position": 6, "name": 'sales_rank_jun_avg' },
        { "position": 7, "name": 'sales_rank_jul_avg' },
        { "position": 8, "name": 'sales_rank_aug_avg' },
        { "position": 9, "name": 'sales_rank_sep_avg' },
        { "position": 10, "name": 'sales_rank_oct_avg' },
        { "position": 11, "name": 'sales_rank_nov_avg' },
        { "position": 12, "name": 'sales_rank_dec_avg' }
      ] },
      { "name": 'Wantlist Export', "fields": [
        { "position": 0, "name": 'isbn' },
        { "position": 1, "name": 'total_quantity_supplier' },
        { "position": 2, "name": 'total_quantity' },
        { "position": 3, "name": 'fbaq' },
        { "position": 4, "name": 'inbq' },
        { "position": 5, "name": 'orq_total' },
        { "position": 6, "name": 'author' },
        { "position": 7, "name": 'title' },
        { "position": 8, "name": 'edition' },
        { "position": 9, "name": 'grade' },
        { "position": 10, "name": 'edition_status_code' },
        { "position": 11, "name": 'edition_status_date' },
        { "position": 12, "name": 'list_price' },
        { "position": 13, "name": 'used_wholesale_price' },
        { "position": 14, "name": 'follet_wh' },
        { "position": 15, "name": 'nebraska_wh' },
        { "position": 16, "name": 'qa_aug_low' },
        { "position": 17, "name": 'qa_low' },
        { "position": 18, "name": 'qa_fba_low' },
        { "position": 19, "name": 'qa_rent' },
        { "position": 20, "name": 'qa_jan_rank' },
        { "position": 21, "name": 'qa_aug_rank' },
        { "position": 22, "name": 'qa_sales_rank' },
        { "position": 23, "name": 'publisher' },
        { "position": 24, "name": 'publication_date' },
        { "position": 25, "name": 'monthly_sqf' },
        { "position": 26, "name": 'monthly_spf' },
        { "position": 27, "name": 'monthly_rqf' },
        { "position": 28, "name": 'monthly_rpf' },
        { "position": 29, "name": 'r_life' },
        { "position": 30, "name": 'oe_aug_rank' },
        { "position": 31, "name": 'oe_isbn' },
        { "position": 32, "name": 'book_scouter_1' },
        { "position": 33, "name": 'book_scouter_2' },
        { "position": 34, "name": 'book_scouter_3' },
        { "position": 35, "name": 'book_scouter_4' },
        { "position": 36, "name": 'ean' },
        { "position": 37, "name": 'one_eighty_sale_quantity_all' },
        { "position": 38, "name": 'one_eighty_sale_price_all' }
      ] },
      { "name": 'DirectMovers', "fields": [
        { "position": 0, "name": 'isbn' },
        { "position":  1, "name": 'total_quantity_supplier' },
        { "position":  2, "name": 'total_quantity' },
        { "position":  3, "name": 'fbaq' },
        { "position":  4, "name": 'orq_total' },
        { "position":  5, "name": 'author' },
        { "position":  6, "name": 'title' },
        { "position":  7, "name": 'edition' },
        { "position":  8, "name": 'grade' },
        { "position":  9, "name": 'edition_status_code' },
        { "position":  10, "name": 'edition_status_date' },
        { "position":  11, "name": 'list_price' },
        { "position":  12, "name": 'used_wholesale_price' },
        { "position":  13, "name": 'follet_wh' },
        { "position":  14, "name": 'nebraska_wh' },
        { "position":  15, "name": 'qa_aug_low' },
        { "position":  16, "name": 'qa_low' },
        { "position":  17, "name": 'qa_fba_low' },
        { "position":  18, "name": 'qa_rent' },
        { "position":  19, "name": 'qa_jan_rank' },
        { "position":  20, "name": 'qa_aug_rank' },
        { "position":  21, "name": 'qa_sales_rank' },
        { "position":  22, "name": 'publisher' },
        { "position":  23, "name": 'publication_date' },
        { "position":  24, "name": 'weekly_sqf' },
        { "position":  25, "name": 'weekly_spf' },
        { "position":  26, "name": 'weekly_rqf' },
        { "position":  27, "name": 'weekly_rpf' },
        { "position":  28, "name": 'weekly_direct_qty_all' },
        { "position":  29, "name": 'weekly_direct_price_all' },
        { "position":  30, "name": 'weekly_direct_qty_main' },
        { "position":  31, "name": 'pricing_custom_2' }
      ] },
      { "name": 'Store Restock Export', "fields": [
        { "position": 0, "name": 'ean' },
        { "position": 1, "name": 'isbn' },
        { "position": 2, "name": 'total_quantity' },
        { "position": 3, "name": 'fbaq' },
        { "position": 4, "name": 'inbq' },
        { "position": 5, "name": 'orq' },
        { "position": 6, "name": 'author' },
        { "position": 7, "name": 'title' },
        { "position": 8, "name": 'edition' },
        { "position": 9, "name": 'grade' },
        { "position": 10, "name": 'edition_status_code' },
        { "position": 11, "name": 'edition_status_date' },
        { "position": 12, "name": 'list_price' },
        { "position": 13, "name": 'used_wholesale_price' },
        { "position": 14, "name": 'follet_wh' },
        { "position": 15, "name": 'nebraska_wh' },
        { "position": 16, "name": 'qa_aug_low' },
        { "position": 17, "name": 'qa_low' },
        { "position": 18, "name": 'qa_fba_low' },
        { "position": 19, "name": 'pricing_custom_12' },
        { "position": 20, "name": 'qa_rent' },
        { "position": 21, "name": 'pricing_custom_15' },
        { "position": 22, "name": 'qa_jan_rank' },
        { "position": 23, "name": 'qa_aug_rank' },
        { "position": 24, "name": 'qa_sales_rank' },
        { "position": 25, "name": 'publisher' },
        { "position": 26, "name": 'publication_date' },
        { "position": 27, "name": 'monthly_sqf' },
        { "position": 28, "name": 'monthly_spf' },
        { "position": 29, "name": 'monthly_rqf' },
        { "position": 30, "name": 'monthly_rpf' },
        { "position": 31, "name": 'one_eighty_sale_quantity_fbaz' },
        { "position": 32, "name": 'one_eighty_spf' },
        { "position": 33, "name": 'one_eighty_rqf' },
        { "position": 34, "name": 'one_eighty_rpf' },
        { "position": 35, "name": 'yearly_low' },
        { "position": 36, "name": 'yearly_fba_low' },
        { "position": 37, "name": 'yearly_main_sold_quantity' },
        { "position": 38, "name": 'yearly_fbaz_sold_quantity' },
        { "position": 39, "name": 'yearly_fbaz_rented_quantity' },
        { "position": 40, "name": 'monthly_sqm' },
        { "position": 41, "name": 'monthly_spm' },
        { "position": 42, "name": 'monthly_direct_qty_all' },
        { "position": 43, "name": 'monthly_direct_price_all' },
        { "position": 44, "name": 'one_year_highest_wholesale_price' },
        { "position": 45, "name": 'two_years_wh_max' },
        { "position": 46, "name": 'amazon_price' },
        { "position": 47, "name": 'lowest_good_price' },
        { "position": 48, "name": 'binding' },
        { "position": 49, "name": 'oe_isbn' },
        { "position": 50, "name": 'oe_aug_rank' }
      ] },
      { "name": 'Historical Data Export', "fields": [
        { "position": 0, "name": 'ean' },
        { "position": 1, "name": 'isbn' },
        { "position": 2, "name": 'low_jan_avg' },
        { "position": 3, "name": 'low_feb_avg' },
        { "position": 4, "name": 'low_mar_avg' },
        { "position": 5, "name": 'low_apr_avg' },
        { "position": 6, "name": 'low_may_avg' },
        { "position": 7, "name": 'low_jun_avg' },
        { "position": 8, "name": 'low_jul_avg' },
        { "position": 9, "name": 'low_aug_avg' },
        { "position": 10, "name": 'low_sep_avg' },
        { "position": 11, "name": 'low_oct_avg' },
        { "position": 12, "name": 'low_nov_avg' },
        { "position": 13, "name": 'low_dec_avg' },
        { "position": 14, "name": 'fba_jan_avg' },
        { "position": 15, "name": 'fba_feb_avg' },
        { "position": 16, "name": 'fba_mar_avg' },
        { "position": 17, "name": 'fba_apr_avg' },
        { "position": 18, "name": 'fba_may_avg' },
        { "position": 19, "name": 'fba_jun_avg' },
        { "position": 20, "name": 'fba_jul_avg' },
        { "position": 21, "name": 'fba_aug_avg' },
        { "position": 22, "name": 'fba_sep_avg' },
        { "position": 23, "name": 'fba_oct_avg' },
        { "position": 24, "name": 'fba_nov_avg' },
        { "position": 25, "name": 'fba_dec_avg' },
        { "position": 26, "name": 'sales_rank_jan_avg' },
        { "position": 27, "name": 'sales_rank_feb_avg' },
        { "position": 28, "name": 'sales_rank_mar_avg' },
        { "position": 29, "name": 'sales_rank_apr_avg' },
        { "position": 30, "name": 'sales_rank_may_avg' },
        { "position": 31, "name": 'sales_rank_jun_avg' },
        { "position": 32, "name": 'sales_rank_jul_avg' },
        { "position": 33, "name": 'sales_rank_aug_avg' },
        { "position": 34, "name": 'sales_rank_sep_avg' },
        { "position": 35, "name": 'sales_rank_oct_avg' },
        { "position": 36, "name": 'sales_rank_nov_avg' },
        { "position": 37, "name": 'sales_rank_dec_avg' },
        { "position": 38, "name": 'one_year_highest_wholesale_price' },
        { "position": 39, "name": 'two_years_wh_max' },
        { "position": 40, "name": 'oe_aug_rank' },
        { "position": 41, "name": 'sales_rank_jan_average' },
        { "position": 42, "name": 'sales_rank_aug_average' }
      ] },
      { "name": 'Store FBA Ship', "fields": [
        { "position": 0, "name": 'isbn' },
        { "position": 1, "name": 'author' },
        { "position": 2, "name": 'title' },
        { "position": 3, "name": 'edition' },
        { "position": 4, "name": 'edition_status_code' },
        { "position": 5, "name": 'edition_status_date' },
        { "position": 6, "name": 'list_price' },
        { "position": 7, "name": 'used_wholesale_price' },
        { "position": 8, "name": 'nebraska_wh' },
        { "position": 9, "name": 'qa_aug_low' },
        { "position": 10, "name": 'lowest_good_price' },
        { "position": 11, "name": 'qa_low' },
        { "position": 12, "name": 'yearly_low' },
        { "position": 13, "name": 'qa_fba_low' },
        { "position": 14, "name": 'monthly_sqf' },
        { "position": 15, "name": 'monthly_spf' },
        { "position": 16, "name": 'monthly_rqf' },
        { "position": 17, "name": 'monthly_rpf' },
        { "position": 18, "name": 'one_year_highest_wholesale_price' },
        { "position": 19, "name": 'two_years_wh_max' },
        { "position": 20, "name": 'publisher' },
        { "position": 21, "name": 'publication_date' },
        { "position": 22, "name": 'weight' },
        { "position": 23, "name": 'amazon_price' }
      ] },
      { "name": 'P&L', "fields": [
        { "position": 0, "name": 'isbn' },
        { "position": 1, "name": 'total_quantity' },
        { "position": 2, "name": 'fbaq' },
        { "position": 3, "name": 'orq_total' },
        { "position": 4, "name": 'author' },
        { "position": 5, "name": 'title' },
        { "position": 6, "name": 'edition' },
        { "position": 7, "name": 'grade' },
        { "position": 8, "name": 'edition_status_code' },
        { "position": 9, "name": 'edition_status_date' },
        { "position": 10, "name": 'list_price' },
        { "position": 11, "name": 'max_all_wholesale_price' },
        { "position": 12, "name": 'qa_aug_low' },
        { "position": 13, "name": 'qa_low' },
        { "position": 14, "name": 'qa_fba_low' },
        { "position": 15, "name": 'qa_rent' },
        { "position": 16, "name": 'qa_jan_rank' },
        { "position": 17, "name": 'qa_aug_rank' },
        { "position": 18, "name": 'qa_sales_rank' },
        { "position": 19, "name": 'publisher' },
        { "position": 20, "name": 'publication_date' },
        { "position": 21, "name": 'ninety_sold_quantity_main' },
        { "position": 22, "name": 'ninety_sold_price_main' },
        { "position": 23, "name": 'amazon_orders_90ds' },
        { "position": 24, "name": 'ninety_spf' },
        { "position": 25, "name": 'ninety_rqf' },
        { "position": 26, "name": 'ninety_rpf' }
      ] },
      { "name": 'Bid Template', "fields": [
        { "position": 0, "name": 'isbn' },
        { "position": 1, "name": 'total_quantity_supplier' },
        { "position": 2, "name": 'total_quantity' },
        { "position": 3, "name": 'fbaq' },
        { "position": 4, "name": 'inbq' },
        { "position": 5, "name": 'orq_total' },
        { "position": 6, "name": 'author' },
        { "position": 7, "name": 'title' },
        { "position": 8, "name": 'edition' },
        { "position": 9, "name": 'grade' },
        { "position": 10, "name": 'edition_status_code' },
        { "position": 11, "name": 'edition_status_date' },
        { "position": 12, "name": 'list_price' },
        { "position": 13, "name": 'used_wholesale_price' },
        { "position": 14, "name": 'nebraska_wh' },
        { "position": 15, "name": 'qa_aug_low' },
        { "position": 16, "name": 'yearly_low' },
        { "position": 17, "name": 'qa_low' },
        { "position": 18, "name": 'qa_fba_low' },
        { "position": 19, "name": 'qa_rent' },
        { "position": 20, "name": 'qa_jan_rank' },
        { "position": 21, "name": 'qa_aug_rank' },
        { "position": 22, "name": 'qa_sales_rank' },
        { "position": 23, "name": 'publisher' },
        { "position": 24, "name": 'publication_date' },
        { "position": 25, "name": 'one_eighty_sale_quantity_fbaz' },
        { "position": 26, "name": 'one_eighty_spf' },
        { "position": 27, "name": 'one_eighty_rqf' },
        { "position": 28, "name": 'one_eighty_rpf' },
        { "position": 29, "name": 'yearly_main_sold_quantity' },
        { "position": 30, "name": 'yearly_fbaz_sold_quantity' },
        { "position": 31, "name": 'yearly_fbaz_rented_quantity' },
        { "position": 32, "name": 'ean' }
      ] },
      { "name": '180', "fields": [
        { "position": 0, "name": 'isbn' },
        { "position": 1, "name": 'one_eighty_sale_quantity_all' },
        { "position": 2, "name": 'one_eighty_sale_price_all' },
        { "position": 3, "name": 'one_eighty_sale_quantity_main' },
        { "position": 4, "name": 'one_eighty_sale_price_main' }
      ] },
      { "name": 'Buyers Guide', "fields": [
        { "position": 0, "name": 'isbn' },
        { "position": 1, "name": 'total_quantity_supplier' },
        { "position": 2, "name": 'total_quantity' },
        { "position": 3, "name": 'fbaq' },
        { "position": 4, "name": 'inbq' },
        { "position": 5, "name": 'orq_total' },
        { "position": 6, "name": 'author' },
        { "position": 7, "name": 'title' },
        { "position": 8, "name": 'edition' },
        { "position": 9, "name": 'grade' },
        { "position": 10, "name": 'edition_status_code' },
        { "position": 11, "name": 'edition_status_date' },
        { "position": 12, "name": 'list_price' },
        { "position": 13, "name": 'used_wholesale_price' },
        { "position": 14, "name": 'nebraska_wh' },
        { "position": 15, "name": 'qa_aug_low' },
        { "position": 16, "name": 'yearly_low' },
        { "position": 17, "name": 'lowest_good_price' },
        { "position": 18, "name": 'qa_low' },
        { "position": 19, "name": 'qa_fba_low' },
        { "position": 20, "name": 'qa_rent' },
        { "position": 21, "name": 'qa_jan_rank' },
        { "position": 22, "name": 'qa_aug_rank' },
        { "position": 23, "name": 'qa_sales_rank' },
        { "position": 24, "name": 'publisher' },
        { "position": 25, "name": 'publication_date' },
        { "position": 26, "name": 'one_eighty_sale_quantity_fbaz' },
        { "position": 27, "name": 'one_eighty_spf' },
        { "position": 28, "name": 'one_eighty_rqf' },
        { "position": 29, "name": 'one_eighty_rpf' },
        { "position": 30, "name": 'book_scouter_1' },
        { "position": 31, "name": 'book_scouter_2' },
        { "position": 32, "name": 'one_eighty_sale_quantity_main' },
        { "position": 33, "name": 'one_eighty_sale_price_main' },
        { "position": 34, "name": 'one_year_highest_wholesale_price' },
        { "position": 35, "name": 'two_years_wh_max' },
        { "position": 36, "name": 'yearly_main_sold_quantity' },
        { "position": 37, "name": 'yearly_fbaz_sold_quantity' },
        { "position": 38, "name": 'yearly_fbaz_rented_quantity' },
        { "position": 39, "name": 'new_box' },
        { "position": 40, "name": 'amazon_price' },
        { "position": 41, "name": 'binding' },
        { "position": 42, "name": 'weight' },
        { "position": 43, "name": 'book_scouter_3' },
        { "position": 44, "name": 'book_scouter_4' },
        { "position": 45, "name": 'oe_isbn' },
        { "position": 46, "name": 'oe_aug_rank' },
        { "position": 47, "name": 'r_life' },
        { "position": 48, "name": 'valore_low' },
        { "position": 49, "name": 'valore_pending_order' },
        { "position": 50, "name": 'oe_yearly_main_sold_quantity' },
        { "position": 51, "name": 'oe_yearly_fbaz_sold_quantity' },
        { "position": 52, "name": 'oe_yearly_fbaz_rented_quantity' },
        { "position": 53, "name": 'oe_one_year_highest_wholesale_price' },
        { "position": 54, "name": 'oe_two_years_wh_max' },
        { "position": 55, "name": 'oe_list_price' },
        { "position": 56, "name": 'comments' },
        { "position": 57, "name": 'orq' },
        { "position": 58, "name": 'ean' }
      ] },
      { "name": 'Rental Whitelist', "fields": [
        { "position": 0, "name": 'isbn' },
        { "position": 1, "name": 'author' },
        { "position": 2, "name": 'title' },
        { "position": 3, "name": 'edition' },
        { "position": 4, "name": 'edition_status_code' },
        { "position": 5, "name": 'edition_status_date' },
        { "position": 6, "name": 'list_price' },
        { "position": 7, "name": 'qa_low' },
        { "position": 8, "name": 'qa_fba_low' },
        { "position": 9, "name": 'qa_sales_rank' },
        { "position": 10, "name": 'publisher' },
        { "position": 11, "name": 'publication_date' },
        { "position": 12, "name": 'lowest_rental' },
        { "position": 13, "name": 'amazon_rental' },
        { "position": 14, "name": 'monthly_nw' },
        { "position": 15, "name": 'monthly_w' },
        { "position": 16, "name": 'ninety_nw' },
        { "position": 17, "name": 'ninety_w' },
        { "position": 18, "name": 'one_eighty_nw' },
        { "position": 19, "name": 'one_eighty_w' },
        { "position": 20, "name": 'one_eighty_rqf' },
        { "position": 21, "name": 'one_eighty_rpf' },
        { "position": 22, "name": 'binding' },
        { "position": 23, "name": 'total_quantity' },
        { "position": 24, "name": 'fbaq' },
        { "position": 25, "name": 'inbq' },
        { "position": 26, "name": 'copyright' }
      ] },
      { "name": 'Restock Review', "fields": [
        { "position": 0, "name": 'isbn' },
        { "position": 1, "name": 'total_quantity' },
        { "position": 2, "name": 'fbaq' },
        { "position": 3, "name": 'inbq' },
        { "position": 4, "name": 'orq' },
        { "position": 5, "name": 'author' },
        { "position": 6, "name": 'title' },
        { "position": 7, "name": 'edition' },
        { "position": 8, "name": 'grade' },
        { "position": 9, "name": 'edition_status_code' },
        { "position": 10, "name": 'edition_status_date' },
        { "position": 11, "name": 'list_price' },
        { "position": 12, "name": 'used_wholesale_price' },
        { "position": 13, "name": 'nebraska_wh' },
        { "position": 14, "name": 'qa_aug_low' },
        { "position": 15, "name": 'qa_low' },
        { "position": 16, "name": 'qa_fba_low' },
        { "position": 17, "name": 'pricing_custom_15' },
        { "position": 18, "name": 'qa_jan_rank' },
        { "position": 19, "name": 'qa_aug_rank' },
        { "position": 20, "name": 'qa_sales_rank' },
        { "position": 21, "name": 'publisher' },
        { "position": 22, "name": 'publication_date' },
        { "position": 23, "name": 'weekly_sqf' },
        { "position": 24, "name": 'weekly_spf' },
        { "position": 25, "name": 'weekly_rqf' },
        { "position": 26, "name": 'weekly_rpf' },
        { "position": 27, "name": 'monthly_sqf' },
        { "position": 28, "name": 'monthly_spf' },
        { "position": 29, "name": 'monthly_rqf' },
        { "position": 30, "name": 'monthly_rpf' },
        { "position": 31, "name": 'monthly_sqm' },
        { "position": 32, "name": 'monthly_spm' },
        { "position": 33, "name": 'weekly_direct_qty_all' },
        { "position": 34, "name": 'weekly_direct_price_all' },
        { "position": 35, "name": 'monthly_direct_qty_all' },
        { "position": 36, "name": 'monthly_direct_price_all' }
      ] },
      { "name": 'Test', "fields": [
        { "position": 0, "name": 'isbn' },
        { "position": 1, "name": 'ean' },
        { "position": 2, "name": 'publisher' }
      ] }
    ]
    templates.each do |template|
      new_template = BookExportTemplate.new(name: template[:name])
      fields = template[:fields]
      fields.each do |field|
        field_mapping = BookFieldMapping.find_by(lookup_field: field[:name])
        if field_mapping.nil?
          puts "Could not find Field Mapping: #{field[:name]} for template: #{template[:name]}"
          break
        else
          new_template.book_export_template_field_mappings.build(
            book_field_mapping_id: field_mapping.id,
            position: field[:position]
          )
        end
      end
      if new_template.save
        puts "Created template: #{new_template.name}"
      else
        puts "Failed to create template: #{template[:name]}, errors: #{new_template.errors.messages}"
      end
    end
  end
end
# rubocop:enable  Metrics/BlockLength
