AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - bin/*
    - db/migrate/*
    - db/schema.rb
    - node_modules/**/*
    - tmp/**/*
    - spec/rails_helper.rb
    - spec/spec_helper.rb
    - Rakefile
    - config.ru

Layout/LineLength:
  Max: 110
  IgnoredPatterns: ['(\A|\s)#']

Metrics/BlockLength:
  Max: 50

Metrics/AbcSize:
  Max: 60

Metrics/MethodLength:
  Max: 50

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true
