class DropIndexFromBooks < ActiveRecord::Migration[6.0]
  def change
      remove_index :books, :amazon_ca_listing
      remove_index :books, :amazon_ca_low
      remove_index :books, :amazon_ca_new
      remove_index :books, :amazon_price
      remove_index :books, :amazon_rental
      remove_index :books, :amazon_rental_average
      remove_index :books, :amazon_uk_low
      remove_index :books, :amazon_uk_new
      remove_index :books, :august_rush_in_stock
      remove_index :books, :author
      remove_index :books, :average_turns
      remove_index :books, :binding
      remove_index :books, :book_scouter_1
      remove_index :books, :book_scouter_2
      remove_index :books, :book_scouter_3
      remove_index :books, :book_scouter_4
      remove_index :books, :book_scouter_5
      remove_index :books, :book_scouter_6
      remove_index :books, :book_scouter_7
      remove_index :books, :book_scouter_vendor_1
      remove_index :books, :book_scouter_vendor_2
      remove_index :books, :book_scouter_vendor_3
      remove_index :books, :book_scouter_vendor_4
      remove_index :books, :book_scouter_vendor_5
      remove_index :books, :book_scouter_vendor_6
      remove_index :books, :book_scouter_vendor_7
      remove_index :books, :buyouts
      remove_index :books, :buyouts_percentage
      remove_index :books, :bz_j_sku_quantity
      remove_index :books, :c_life
      remove_index :books, :comments
      remove_index :books, :competitive_sellers
      remove_index :books, :copyright
      remove_index :books, :copyright_year
      remove_index :books, :edition
      remove_index :books, :edition_flag
      remove_index :books, :edition_status_code
      remove_index :books, :edition_status_date
      remove_index :books, :email_price
      remove_index :books, :fba_apr_avg
      remove_index :books, :fba_aug_avg
      remove_index :books, :fba_dec_avg
      remove_index :books, :fba_feb_avg
      remove_index :books, :fba_jan_avg
      remove_index :books, :fba_jul_avg
      remove_index :books, :fba_jun_avg
      remove_index :books, :fba_mar_avg
      remove_index :books, :fba_may_avg
      remove_index :books, :fba_nov_avg
      remove_index :books, :fba_oct_avg
      remove_index :books, :fba_price
      remove_index :books, :fba_sellers
      remove_index :books, :fba_sep_avg
      remove_index :books, :fba_seventh
      remove_index :books, :fba_sku_quantity
      remove_index :books, :fbaq
      remove_index :books, :fbaz_flag
      remove_index :books, :fbaz_low
      remove_index :books, :fcb_price
      remove_index :books, :forty_percent_rental
      remove_index :books, :grade
      remove_index :books, :grid_lowest
      remove_index :books, :highest_weekly_low
      remove_index :books, :highest_weekly_low_average_last_seven_thirty
      remove_index :books, :image_url
      remove_index :books, :inbq
      remove_index :books, :jan_rush_in_stock
      remove_index :books, :last_scanned
      remove_index :books, :list_price
      remove_index :books, :low_apr_avg
      remove_index :books, :low_aug_avg
      remove_index :books, :low_dec_avg
      remove_index :books, :low_feb_avg
      remove_index :books, :low_jan_avg
      remove_index :books, :low_jul_avg
      remove_index :books, :low_jun_avg
      remove_index :books, :low_mar_avg
      remove_index :books, :low_may_avg
      remove_index :books, :low_nov_avg
      remove_index :books, :low_oct_avg
      remove_index :books, :low_sep_avg
      remove_index :books, :lowest_good_price
      remove_index :books, :lowest_price
      remove_index :books, :lowest_price_aug_average
      remove_index :books, :lowest_price_jan_average
      remove_index :books, :lowest_rental
      remove_index :books, :lowest_rental_average
      remove_index :books, :main_fifth_price
      remove_index :books, :main_flag
      remove_index :books, :main_min_price
      remove_index :books, :main_price
      remove_index :books, :main_quantity_in_inventory
      remove_index :books, :manual_add
      remove_index :books, :max_used_wholesale_price
      remove_index :books, :max_wholesale_comments
      remove_index :books, :max_wholesale_price
      remove_index :books, :monthly_amazon_trade_in
      remove_index :books, :monthly_direct_price_all
      remove_index :books, :monthly_direct_price_main
      remove_index :books, :monthly_direct_qty_all
      remove_index :books, :monthly_fba
      remove_index :books, :monthly_low
      remove_index :books, :monthly_nw
      remove_index :books, :monthly_rc
      remove_index :books, :monthly_rpf
      remove_index :books, :monthly_rqf
      remove_index :books, :monthly_sold_price_all
      remove_index :books, :monthly_sold_quantity_all
      remove_index :books, :monthly_sold_quantity_direct
      remove_index :books, :monthly_spf
      remove_index :books, :monthly_spm
      remove_index :books, :monthly_sqf
      remove_index :books, :monthly_sqm
      remove_index :books, :monthly_w
      remove_index :books, :nebraska_wh
      remove_index :books, :new_box
      remove_index :books, :new_edition_date
      remove_index :books, :new_wholesale_price
      remove_index :books, :ninety_accepted
      remove_index :books, :ninety_fba
      remove_index :books, :ninety_low
      remove_index :books, :ninety_nw
      remove_index :books, :ninety_rpf
      remove_index :books, :ninety_rqf
      remove_index :books, :ninety_sold_price_all
      remove_index :books, :ninety_sold_price_main
      remove_index :books, :ninety_sold_quantity_all
      remove_index :books, :ninety_sold_quantity_main
      remove_index :books, :ninety_spf
      remove_index :books, :ninety_w
      remove_index :books, :not_in_guide
      remove_index :books, :not_on_amazon
      remove_index :books, :nw_apr_avg
      remove_index :books, :nw_aug_avg
      remove_index :books, :nw_dec_avg
      remove_index :books, :nw_feb_avg
      remove_index :books, :nw_jan_avg
      remove_index :books, :nw_jul_avg
      remove_index :books, :nw_jun_avg
      remove_index :books, :nw_mar_avg
      remove_index :books, :nw_may_avg
      remove_index :books, :nw_nov_avg
      remove_index :books, :nw_oct_avg
      remove_index :books, :nw_sep_avg
      remove_index :books, :oe_isbn
      remove_index :books, :oe_life
      remove_index :books, :one_eighty_fba
      remove_index :books, :one_eighty_low
      remove_index :books, :one_eighty_nw
      remove_index :books, :one_eighty_rc
      remove_index :books, :one_eighty_rpf
      remove_index :books, :one_eighty_rqf
      remove_index :books, :one_eighty_sale_price_all
      remove_index :books, :one_eighty_sale_price_main
      remove_index :books, :one_eighty_sale_quantity_all
      remove_index :books, :one_eighty_sale_quantity_fbaz
      remove_index :books, :one_eighty_sale_quantity_main
      remove_index :books, :one_eighty_spf
      remove_index :books, :one_eighty_w
      remove_index :books, :one_year_highest_wholesale_price
      remove_index :books, :orq
      remove_index :books, :orq_ninety
      remove_index :books, :orq_total
      remove_index :books, :out_of_print_date
      remove_index :books, :pricing_custom_12
      remove_index :books, :pricing_custom_14
      remove_index :books, :pricing_custom_15
      remove_index :books, :pricing_custom_2
      remove_index :books, :publication_date
      remove_index :books, :publisher
      remove_index :books, :qa_aug_low
      remove_index :books, :qa_aug_rank
      remove_index :books, :qa_fba_low
      remove_index :books, :qa_jan_rank
      remove_index :books, :qa_low
      remove_index :books, :qa_notes
      remove_index :books, :qa_rent
      remove_index :books, :qa_sales_rank
      remove_index :books, :r_life
      remove_index :books, :rc
      remove_index :books, :rental_history
      remove_index :books, :returns
      remove_index :books, :returns_percentage
      remove_index :books, :roi
      remove_index :books, :sales_rank
      remove_index :books, :sales_rank_apr_avg
      remove_index :books, :sales_rank_aug_average
      remove_index :books, :sales_rank_aug_avg
      remove_index :books, :sales_rank_dec_avg
      remove_index :books, :sales_rank_feb_avg
      remove_index :books, :sales_rank_jan_average
      remove_index :books, :sales_rank_jan_avg
      remove_index :books, :sales_rank_jul_avg
      remove_index :books, :sales_rank_jun_avg
      remove_index :books, :sales_rank_mar_avg
      remove_index :books, :sales_rank_may_avg
      remove_index :books, :sales_rank_nov_avg
      remove_index :books, :sales_rank_oct_avg
      remove_index :books, :sales_rank_sep_avg
      remove_index :books, :scraped_date
      remove_index :books, :sku
      remove_index :books, :store_name
      remove_index :books, :subject
      remove_index :books, :supplier_low
      remove_index :books, :supplier_price
      remove_index :books, :texas_wh
      remove_index :books, :third_fba
      remove_index :books, :three_years_fbaz_rented_quantity
      remove_index :books, :three_years_fbaz_sold_quantity
      remove_index :books, :three_years_main_sold_quantity
      remove_index :books, :three_years_sold_quantity_all
      remove_index :books, :title
      remove_index :books, :total_offers
      remove_index :books, :total_quantity
      remove_index :books, :total_quantity_supplier
      remove_index :books, :trade_flag
      remove_index :books, :two_years_fbaz_rented_quantity
      remove_index :books, :two_years_fbaz_sold_quantity
      remove_index :books, :two_years_main_sold_quantity
      remove_index :books, :two_years_sold_quantity_all
      remove_index :books, :two_years_wh_max
      remove_index :books, :two_years_wh_min
      remove_index :books, :uploaded_to_s3
      remove_index :books, :used_wholesale_price
      remove_index :books, :valore_pending_order
      remove_index :books, :weekly_chegg_sale_quantity
      remove_index :books, :weekly_direct_price_all
      remove_index :books, :weekly_direct_qty_all
      remove_index :books, :weekly_direct_qty_main
      remove_index :books, :weekly_fba
      remove_index :books, :weekly_low
      remove_index :books, :weekly_rpf
      remove_index :books, :weekly_rqf
      remove_index :books, :weekly_sale_price_all
      remove_index :books, :weekly_sale_quantity_all
      remove_index :books, :weekly_sales_rank
      remove_index :books, :weekly_spf
      remove_index :books, :weekly_spm
      remove_index :books, :weekly_sqf
      remove_index :books, :weekly_sqm
      remove_index :books, :weekly_tradein
      remove_index :books, :weight
      remove_index :books, :yearly_fba_low
      remove_index :books, :yearly_fbaz_rented_quantity
      remove_index :books, :yearly_fbaz_sold_quantity
      remove_index :books, :yearly_low
      remove_index :books, :yearly_main_sold_quantity
      remove_index :books, :yearly_sold_quantity_all
  end
end
