class LimitBooksNumericFieldsDecimal < ActiveRecord::Migration[6.0]
  def up
    change_column :books,:book_scouter_1,:decimal, precision: 10, scale: 2
    change_column :books,:book_scouter_2,:decimal, precision: 10, scale: 2
    change_column :books,:book_scouter_3,:decimal, precision: 10, scale: 2
    change_column :books,:book_scouter_4,:decimal, precision: 10, scale: 2
    change_column :books,:book_scouter_5,:decimal, precision: 10, scale: 2
    change_column :books,:book_scouter_6,:decimal, precision: 10, scale: 2
    change_column :books,:book_scouter_7,:decimal, precision: 10, scale: 2
    change_column :books,:list_price,:decimal, precision: 10, scale: 2
    change_column :books,:used_wholesale_price,:decimal, precision: 10, scale: 2
    change_column :books,:new_wholesale_price,:decimal, precision: 10, scale: 2
    change_column :books,:amazon_price,:decimal, precision: 10, scale: 2
    change_column :books,:lowest_good_price,:decimal, precision: 10, scale: 2
    change_column :books,:lowest_price,:decimal, precision: 10, scale: 2
    change_column :books,:amazon_rental,:decimal, precision: 10, scale: 2
    change_column :books,:lowest_rental,:decimal, precision: 10, scale: 2
    change_column :books,:fcb_price,:decimal, precision: 10, scale: 2
    change_column :books,:fba_price,:decimal, precision: 10, scale: 2
    change_column :books,:amazon_rental_average,:decimal, precision: 10, scale: 2
    change_column :books,:lowest_rental_average,:decimal, precision: 10, scale: 2
    change_column :books,:lowest_price_aug_average,:decimal, precision: 10, scale: 2
    change_column :books,:lowest_price_jan_average,:decimal, precision: 10, scale: 2
    change_column :books,:pricing_custom_2,:decimal, precision: 10, scale: 2
    change_column :books,:max_wholesale_price,:decimal, precision: 10, scale: 2
    change_column :books,:amazon_ca_listing,:decimal, precision: 10, scale: 2
    change_column :books,:pricing_custom_15,:decimal, precision: 10, scale: 2
    change_column :books,:average_turns,:decimal, precision: 10, scale: 2
    change_column :books,:grid_lowest,:decimal, precision: 10, scale: 2
    change_column :books,:weekly_spm,:decimal, precision: 10, scale: 2
    change_column :books,:monthly_spm,:decimal, precision: 10, scale: 2
    change_column :books,:weekly_spf,:decimal, precision: 10, scale: 2
    change_column :books,:weekly_rpf,:decimal, precision: 10, scale: 2
    change_column :books,:monthly_spf,:decimal, precision: 10, scale: 2
    change_column :books,:monthly_rpf,:decimal, precision: 10, scale: 2
    change_column :books,:main_price,:decimal, precision: 10, scale: 2
    change_column :books,:monthly_nw,:decimal, precision: 10, scale: 2
    change_column :books,:monthly_w,:decimal, precision: 10, scale: 2
    change_column :books,:oe_life,:decimal, precision: 10, scale: 2
    change_column :books,:c_life,:decimal, precision: 10, scale: 2
    change_column :books,:r_life,:decimal, precision: 10, scale: 2
    change_column :books,:ninety_nw,:decimal, precision: 10, scale: 2
    change_column :books,:ninety_w,:decimal, precision: 10, scale: 2
    change_column :books,:one_eighty_nw,:decimal, precision: 10, scale: 2
    change_column :books,:one_eighty_w,:decimal, precision: 10, scale: 2
    change_column :books,:monthly_fba,:decimal, precision: 10, scale: 2
    change_column :books,:ninety_low,:decimal, precision: 10, scale: 2
    change_column :books,:one_eighty_low,:decimal, precision: 10, scale: 2
    change_column :books,:ninety_rpf,:decimal, precision: 10, scale: 2
    change_column :books,:ninety_spf,:decimal, precision: 10, scale: 2
    change_column :books,:one_eighty_spf,:decimal, precision: 10, scale: 2
    change_column :books,:one_eighty_rpf,:decimal, precision: 10, scale: 2
    change_column :books,:email_price,:decimal, precision: 10, scale: 2
    change_column :books,:weekly_low,:decimal, precision: 10, scale: 2
    change_column :books,:monthly_low,:decimal, precision: 10, scale: 2
    change_column :books,:ninety_fba,:decimal, precision: 10, scale: 2
    change_column :books,:weekly_fba,:decimal, precision: 10, scale: 2
    change_column :books,:one_eighty_fba,:decimal, precision: 10, scale: 2
    change_column :books,:low_jan_avg,:decimal, precision: 10, scale: 2
    change_column :books,:low_feb_avg,:decimal, precision: 10, scale: 2
    change_column :books,:low_mar_avg,:decimal, precision: 10, scale: 2
    change_column :books,:low_apr_avg,:decimal, precision: 10, scale: 2
    change_column :books,:low_may_avg,:decimal, precision: 10, scale: 2
    change_column :books,:low_jun_avg,:decimal, precision: 10, scale: 2
    change_column :books,:low_jul_avg,:decimal, precision: 10, scale: 2
    change_column :books,:low_aug_avg,:decimal, precision: 10, scale: 2
    change_column :books,:low_sep_avg,:decimal, precision: 10, scale: 2
    change_column :books,:low_oct_avg,:decimal, precision: 10, scale: 2
    change_column :books,:low_nov_avg,:decimal, precision: 10, scale: 2
    change_column :books,:low_dec_avg,:decimal, precision: 10, scale: 2
    change_column :books,:fba_jan_avg,:decimal, precision: 10, scale: 2
    change_column :books,:fba_feb_avg,:decimal, precision: 10, scale: 2
    change_column :books,:fba_mar_avg,:decimal, precision: 10, scale: 2
    change_column :books,:fba_apr_avg,:decimal, precision: 10, scale: 2
    change_column :books,:fba_may_avg,:decimal, precision: 10, scale: 2
    change_column :books,:fba_jun_avg,:decimal, precision: 10, scale: 2
    change_column :books,:fba_jul_avg,:decimal, precision: 10, scale: 2
    change_column :books,:fba_aug_avg,:decimal, precision: 10, scale: 2
    change_column :books,:fba_sep_avg,:decimal, precision: 10, scale: 2
    change_column :books,:fba_oct_avg,:decimal, precision: 10, scale: 2
    change_column :books,:fba_nov_avg,:decimal, precision: 10, scale: 2
    change_column :books,:fba_dec_avg,:decimal, precision: 10, scale: 2
    change_column :books,:weekly_tradein,:decimal, precision: 10, scale: 2
    change_column :books,:nebraska_wh,:decimal, precision: 10, scale: 2
    change_column :books,:texas_wh,:decimal, precision: 10, scale: 2
    change_column :books,:main_min_price,:decimal, precision: 10, scale: 2
    change_column :books,:main_fifth_price,:decimal, precision: 10, scale: 2
    change_column :books,:ninety_accepted,:decimal, precision: 10, scale: 2
    change_column :books,:highest_weekly_low,:decimal, precision: 10, scale: 2
    change_column :books,:pricing_custom_14,:decimal, precision: 10, scale: 2
    change_column :books,:highest_weekly_low_average_last_seven_thirty,:decimal, precision: 10, scale: 2
    change_column :books,:buyouts_percentage,:decimal, precision: 10, scale: 2
    change_column :books,:returns_percentage,:decimal, precision: 10, scale: 2
    change_column :books,:third_fba,:decimal, precision: 10, scale: 2
    change_column :books,:supplier_price,:decimal, precision: 10, scale: 2
    change_column :books,:fbaz_low,:decimal, precision: 10, scale: 2
    change_column :books,:fba_seventh,:decimal, precision: 10, scale: 2
    change_column :books,:roi,:decimal, precision: 10, scale: 2
    change_column :books,:monthly_amazon_trade_in,:decimal, precision: 10, scale: 2
    change_column :books,:yearly_low,:decimal, precision: 10, scale: 2
    change_column :books,:yearly_fba_low,:decimal, precision: 10, scale: 2
    change_column :books,:nw_feb_avg,:decimal, precision: 10, scale: 2
    change_column :books,:nw_mar_avg,:decimal, precision: 10, scale: 2
    change_column :books,:nw_apr_avg,:decimal, precision: 10, scale: 2
    change_column :books,:nw_may_avg,:decimal, precision: 10, scale: 2
    change_column :books,:nw_jun_avg,:decimal, precision: 10, scale: 2
    change_column :books,:nw_jul_avg,:decimal, precision: 10, scale: 2
    change_column :books,:nw_aug_avg,:decimal, precision: 10, scale: 2
    change_column :books,:nw_sep_avg,:decimal, precision: 10, scale: 2
    change_column :books,:nw_oct_avg,:decimal, precision: 10, scale: 2
    change_column :books,:nw_nov_avg,:decimal, precision: 10, scale: 2
    change_column :books,:nw_dec_avg,:decimal, precision: 10, scale: 2
    change_column :books,:weekly_direct_price_all,:decimal, precision: 10, scale: 2
    change_column :books,:monthly_direct_price_all,:decimal, precision: 10, scale: 2
    change_column :books,:monthly_direct_price_main,:decimal, precision: 10, scale: 2
    change_column :books,:one_eighty_sale_price_all,:decimal, precision: 10, scale: 2
    change_column :books,:one_eighty_sale_price_main,:decimal, precision: 10, scale: 2
    change_column :books,:ninety_sold_price_all,:decimal, precision: 10, scale: 2
    change_column :books,:ninety_sold_price_main,:decimal, precision: 10, scale: 2
    change_column :books,:weekly_sale_price_all,:decimal, precision: 10, scale: 2
    change_column :books,:monthly_sold_price_all,:decimal, precision: 10, scale: 2
    change_column :books,:amazon_ca_low,:decimal, precision: 10, scale: 2
    change_column :books,:amazon_ca_new,:decimal, precision: 10, scale: 2
    change_column :books,:amazon_uk_low,:decimal, precision: 10, scale: 2
    change_column :books,:amazon_uk_new,:decimal, precision: 10, scale: 2
    change_column :books,:jan_rush_in_stock,:decimal, precision: 10, scale: 2
    change_column :books,:august_rush_in_stock,:decimal, precision: 10, scale: 2
    change_column :books,:new_box,:decimal, precision: 10, scale: 2
    change_column :books,:forty_percent_rental,:decimal, precision: 10, scale: 2
    change_column :books,:qa_low,:decimal, precision: 10, scale: 2
    change_column :books,:qa_aug_low,:decimal, precision: 10, scale: 2
    change_column :books,:qa_fba_low,:decimal, precision: 10, scale: 2
    change_column :books,:qa_rent,:decimal, precision: 10, scale: 2
    change_column :books,:pricing_custom_12,:decimal, precision: 10, scale: 2
    change_column :books,:two_years_wh_max,:decimal, precision: 10, scale: 2
    change_column :books,:two_years_wh_min,:decimal, precision: 10, scale: 2
    change_column :books,:one_year_highest_wholesale_price,:decimal, precision: 10, scale: 2
    change_column :books,:weight,:decimal, precision: 10, scale: 2
    change_column :books,:nw_jan_avg,:decimal, precision: 10, scale: 2
  end

  def down
  end
end
